### ISSUE TITLE
NullPointerException in WEASEL.createBagOfPatterns

### ISSUE THREAD

**Issue by watanabe8760** [patrickzib/SFA#21] opened 2018-01-25 02:54 UTC
It feels like it's related #17. I encountered the following two errors (different data sets).
There must be an inconsistency between number of elements of `words` expected and actually created.
```java
java.lang.NullPointerException
	at sfa.transformation.WEASEL.createBagOfPatterns(WEASEL.java:147)
	at sfa.classification.WEASELClassifier.fitWeasel(WEASELClassifier.java:162)
	at sfa.classification.WEASELClassifier.fit(WEASELClassifier.java:110)
	at xxxxx.execution.WEASELClassifierCrossValidator.main(WEASELClassifierCrossValidator.java:40)
Exception in thread "main" java.lang.NullPointerException
	at sfa.classification.WEASELClassifier.fit(WEASELClassifier.java:113)
	at xxxxx.execution.WEASELClassifierCrossValidator.main(WEASELClassifierCrossValidator.java:40)

```
```java
java.lang.NullPointerException
	at sfa.transformation.WEASEL.createBagOfPatterns(WEASEL.java:151)
	at sfa.classification.WEASELClassifier.fitWeasel(WEASELClassifier.java:162)
	at sfa.classification.WEASELClassifier.fit(WEASELClassifier.java:110)
	at xxxxx.execution.WEASELClassifierCrossValidator.main(WEASELClassifierCrossValidator.java:40)
Exception in thread "main" java.lang.NullPointerException
	at sfa.classification.WEASELClassifier.fit(WEASELClassifier.java:113)
	at xxxxx.execution.WEASELClassifierCrossValidator.main(WEASELClassifierCrossValidator.java:40)
```

**Comment by patrickzib** [comment] 2018-01-25 14:37
thank you for reporting the bug. 

I am a bit confused as I cannot reproduce it. it seems to me that this error states that there are no words for a given time series of the window length. can you tell me, which array access causes the error? Is it `words[0][j].length`? 

I wrote a testcase with variable length time series but i cannot reproduce this error. there is always at least one element in the words-array. 

I do not want to add a check for `null` there, as the error indicates that something went wrong somewhere else, and no words are generated... 

is there any chance you can give me some more information?

**Comment by patrickzib** [comment] 2018-03-02 12:31
I am closing this now ... If there is still a problem, please update me.

**Closed by patrickzib** 2018-03-02 12:31 UTC
